// examples/example-todo-svelte/src/components/AppBody.svelte
<script lang="ts">
  import { classNames } from '../utils/classNames';
  import TaskListHeader from './TaskListHeader.svelte';
  import TaskInput from './TaskInput.svelte';
  import TaskList from './TaskList.svelte';
</script>

<main class={classNames('w-full flex-1 overflow-y-auto')}>
  <section class="max-w-md h-full m-auto flex flex-col gap-6 px-3">
    <TaskListHeader />
    <TaskInput />
    <TaskList />
  </section>
</main>

// examples/react/fenix-store-todo-react/src/components/AppBody.tsx
import { classNames } from '../utils/classNames';
import { TaskInput } from './TaskInput';
import { TaskList } from './TaskList';
import { TaskListHeader } from './TaskListHeader';

export const AppBody: React.FC = () => {
  return (
    <main className={classNames('w-full flex-1 overflow-y-auto')}>
      <section className="max-w-md h-full m-auto flex flex-col gap-6">
        <TaskListHeader />
        <TaskInput />
        <TaskList />
      </section>
    </main>
  );
};
