// examples/example-todo-svelte/src/components/AppHeader.svelte
<script lang="ts">
  import Switch from '../lib/Switch.svelte';
  import { store } from '../store';

  const darkMode = store.on('darkMode');
  const toggleDarkMode = () => darkMode.update((curr) => !curr);
</script>

<header class="w-full p-4 mb-2 flex items-center">
  <p class="flex-1 text-sm text-gray-500">
    Fenix Store Example - Todo App (Svelte)
  </p>

  <article class="flex items-center gap-3 text-lg">
    <i class="bi bi-sun" />
    <Switch checked={$darkMode} onClick={toggleDarkMode} />
    <i class="bi bi-moon" />
  </article>
</header>

// examples/react/fenix-store-todo-react/src/components/AppHeader.tsx
import { Switch } from '../lib/Switch';
import { useDarkMode } from '../hooks';

export const AppHeader: React.FC = () => {
  const { darkMode, toggleDarkMode } = useDarkMode();

  return (
    <header className="w-full px-4 py-2 flex items-center">
      <p className="flex-1 text-sm text-gray-500">
        Fenix Store Example - Todo App (React)
      </p>

      <article className="flex items-center gap-3 text-lg">
        <i className="bi bi-sun" />
        <Switch checked={darkMode} onClick={toggleDarkMode} />
        <i className="bi bi-moon" />
      </article>
    </header>
  );
};
