// examples/example-todo-svelte/src/components/TaskInput.svelte
<script lang="ts">
  import { store } from '../store';
  import { classNames } from '../utils/classNames';

  let value = '';
  const handleAddTask = () => {
    const id = Date.now().toString();

    store.on(`tasks.items.${id}`).set({
      id,
      completed: false,
      label: value,
    });

    value = '';
  };
</script>

<section class="w-full flex gap-3">
  <input
    class="bg-gray-200 dark:bg-gray-800 py-4 px-6 rounded-xl flex-1"
    placeholder="Enter your next task..."
    bind:value
  />

  <button
    class={classNames(
      'w-13 h-13 p-2',
      'flex items-center justify-center',
      'text-gray-100 dark:text-gray-900 text-2xl',
      'bg-primary-400 dark:bg-primary-500',
      'rounded-xl',
    )}
    on:click={handleAddTask}
  >
    <i class="bi bi-plus-lg" />
  </button>
</section>

// examples/react/fenix-store-todo-react/src/components/TaskInput.tsx
import { useState } from 'react';
import { useTaskList } from '../hooks';
import { classNames } from '../utils/classNames';

export const TaskInput: React.FC = () => {
  const [value, setValue] = useState('');
  const tasks = useTaskList();

  const handleAddTask = () => {
    if (value) {
      tasks.add(value);
      setValue('');
    }
  };

  return (
    <section className="w-full flex gap-3">
      <input
        className="bg-gray-200 dark:bg-gray-800 py-4 px-6 rounded-xl flex-1"
        placeholder="Enter your next task..."
        value={value}
        onChange={(e) => setValue(e.target.value)}
      />

      <button
        className={classNames(
          'w-13 h-13 p-2',
          'flex items-center justify-center',
          'text-gray-100 dark:text-gray-900 text-2xl',
          'bg-primary-400 dark:bg-primary-600',
          'rounded-xl',
        )}
        onClick={handleAddTask}
      >
        <i className="bi bi-plus-lg" />
      </button>
    </section>
  );
};
