// examples/todo-app/fenix-store-todo-svelte/src/components/TaskList.svelte
<script lang="ts">
  import { StorePath, store } from '../store';
  import TaskItem from './TaskItem.svelte';

  const tasks = store.on<string[]>(StorePath.TASK_IDS);
</script>

<section class="flex-1 flex flex-col gap-3 overflow-y-auto">
  {#each $tasks as taskId}
    <TaskItem id={taskId} />
  {/each}
</section>

// examples/example-todo-react/src/components/TaskList.tsx
import { useTaskList } from '../hooks';
import { TaskItem } from './TaskItem';

export const TaskList: React.FC = () => {
  const tasks = useTaskList();

  return (
    <section className="flex-1 flex flex-col gap-3 overflow-y-auto">
      {tasks.map((taskId) => (
        <TaskItem key={taskId} id={taskId} />
      ))}
    </section>
  );
};
