// examples/example-todo-react/src/App.tsx
import { AppBody } from './components/AppBody';
import { AppFooter } from './components/AppFooter';
import { AppHeader } from './components/AppHeader';
import { classNames } from './utils/classNames';
import { useDarkMode } from './hooks';

function App() {
  const darkMode = useDarkMode();

  return (
    <div
      className={classNames(
        'w-full h-full flex flex-col',
        'bg-gray-100 dark:bg-gray-900',
        'text-gray-700 dark:text-gray-300',
        {
          dark: darkMode,
        },
      )}
    >
      <AppHeader />
      <AppBody />
      <AppFooter />
    </div>
  );
}

export default App;

// examples/example-todo-svelte/src/App.svelte
<script lang="ts">
  import AppBody from './components/AppBody.svelte';
  import AppFooter from './components/AppFooter.svelte';
  import AppHeader from './components/AppHeader.svelte';
  import { store } from './store';
  import { classNames } from './utils/classNames';

  const darkMode = store.on('darkMode');
</script>

<div
  class={classNames(
    'w-full h-full flex flex-col',
    'bg-gray-100 dark:bg-gray-900',
    'text-gray-700 dark:text-gray-300',
    {
      dark: $darkMode,
    },
  )}
>
  <AppHeader />
  <AppBody />
  <AppFooter />
</div>
